### ISSUE TITLE
Problem with the alacritty .yml

### ISSUE THREAD

**Issue by manusimon** [FhilipeCrash/Dotfiles#1]
![Captura de pantalla de 2020-11-18 21-13-32](https://user-images.githubusercontent.com/74571940/99582931-11548980-29e3-11eb-8b65-f6454cbc1f87.png)

Im on linux mint, installed allacrity and used your .yml configuration (It looks dope), but i dont know why does it look like that

**Comment by b4skyx** [comment]
Seems to be a font rendering issue to me. Try enabling anti-aliasing or change font in config.

**Comment by fhilipecrash** [comment]
you probably don't have the font installed, download the font or change to another one in the configuration
